POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dana",
    "number": "42323" 
}
###
GET http://localhost:3001/api/persons/670ecbfac707d3e6199b6c82
### 
PUT http://localhost:3001/api/persons/670ecbfac707d3e6199b6c82
Content-Type: application/json

{
    "name": "Bob Noob",
    "number": "1122" 
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/670ec3e7c707d3e6199b6c6a